language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
install:
  - composer self-update
  - composer install
deploy:
  provider: heroku
  on:
    all_branches: true
  api_key:
    secure: 435dd6e6-c324-4c87-ad56-115862b6b355
  run:
    - "sudo apt-get install sqlite3 libsqlite3-dev"
  app:
    master: api-emojicon
    develop: api-emojicon-staging
