language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
install:
  - composer self-update
  - composer install
deploy:
  provider: heroku
  on: develop
  api_key:
    secure: 435dd6e6-c324-4c87-ad56-115862b6b355
  app: api-emojicon
